// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Money_Exchange.API.Infraestructure.Context
{
    public partial class Currency
    {
        public Currency()
        {
            CurrencyValue = new HashSet<CurrencyValue>();
            QueryStartCurrency = new HashSet<Query>();
            QueryTargetCurrency = new HashSet<Query>();
        }

        public int CurrencyId { get; set; }
        public string Description { get; set; }
        public bool Removed { get; set; }
        public int CreatorUserId { get; set; }
        public DateTime CreationDate { get; set; }
        public int? ModifierUserId { get; set; }
        public DateTime? ModificationDate { get; set; }

        public virtual ICollection<CurrencyValue> CurrencyValue { get; set; }
        public virtual ICollection<Query> QueryStartCurrency { get; set; }
        public virtual ICollection<Query> QueryTargetCurrency { get; set; }
    }
}